apiVersion: v2
name: argocd-config
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 9.4.1
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 2.0.4
    repository: https://argoproj.github.io/argo-helm
